- .gitignore
- project/Makefile
- project/scripts/setup.sh
- project/scripts/setup.unix.sh
- project/src/.env.example
- project/src/backend/Dockerfile
- project/src/backend/scripts/entrypoint.sh
- project/src/web/Dockerfile
- project/src/web/scripts/entrypoint.sh
- Add variable to **.env**, only one is needed to setup the whole project
- Update **setup.sh** and fix bug for pull project
- Setup command to auto run **db migration** on init & normal run
- Add dev and prod mode in **entryscript.sh**
> Setup fix db migration

- project/src/backend/app/prisma/dbml/schema.dbml
- project/src/backend/app/prisma/migrations/20230421121217_add_user_password/migration.sql
- project/src/backend/app/prisma/schema.prisma
- project/src/backend/app/src/auth/auth.controller.ts
- project/src/backend/app/src/auth/auth.service.ts
- project/src/web/app/src/components/ui/form/LoginForm.vue
- project/src/web/app/src/router/index.ts
- project/src/web/app/src/views/auth/LoginView.vue
Implemented alternative login system for dev purposes
> feat(login): Added username/pass login

- project/src/web/app/src/components/games/GamesLobby.vue
- project/src/web/app/src/views/games/GamesView.vue
- We can now join a game from the game list when clicking on the `AirplayIcon`
> feat(games): join game from game list

- project/src/backend/app/src/games/games.controller.ts
- project/src/backend/app/src/games/games.service.ts
Added a game statistics endpoint (at the moment only accessible threw the swagger or postman)
- fixes: #22
> feat(games): add a game statistics endpoint

- project/Makefile
- project/src/web/app/src/App.vue
- project/src/web/app/src/assets/stylesheets/partials/base/_themes.scss
- project/src/web/app/src/components/ui/banner/AlertBanner.vue
- project/src/web/app/src/interfaces/alert.interface.ts
- project/src/web/app/src/router/index.ts
- project/src/web/app/src/stores/alert.ts
- project/src/web/app/src/views/NotFoundView.vue
- project/src/web/scripts/entrypoint.sh
Errors response should now be rendered with the following way:
```js
import { useAlertStore } from "@/stores/alert";
import type { AlertInterface } from "@/interfaces/alert.interface";
// example of error structur
const alert = {
status: 401,
message: 'Vous devez être connecté pour accéder à cette page',
} as AlertInterface;
alertStore.setAlert(alert); // will display the banner and then clear it after 5000ms
```
> 23 manage error repsonse messages in view

- project/src/web/app/src/components/games/GamesLobby.vue
- project/src/web/app/src/components/games/GamesSettingsModal.vue
- project/src/web/app/src/components/layout/layout/GameLayout.vue
- project/src/web/app/src/components/ui/form/Modal.vue
- project/src/web/app/src/components/user/playersList.vue
- project/src/web/app/src/interfaces/game.interface.ts
- project/src/web/app/src/services/gameServices.ts
- project/src/web/app/src/stores/gamesSettingsStore.ts
- project/src/web/app/src/views/games/GamesView.vue
In this PR I'have added a player List, to the game layout, A button to create a game, a modal to select the game settings. 
And a store for the game settings
> feat(games): Add game list, game settings, create button, and modal

- project/src/backend/app/src/channels/channels.controller.ts
- project/src/backend/app/src/channels/channels.service.ts
- project/src/web/app/src/components/channels/ChannelList.vue
- project/src/web/app/src/components/channels/ChannelLobby.vue
- project/src/web/app/src/components/layout/layout/ChannelLayout.vue
- project/src/web/app/src/components/ui/button/permissionMemberButton.vue
- project/src/web/app/src/components/user/MembersList.vue
- project/src/web/app/src/components/user/UserCard.vue
- project/src/web/app/src/components/user/UserContextMenu.vue
- project/src/web/app/src/router/index.ts
add button for user permission and status in channel
> Upgrade channel

- project/src/backend/app/src/2fa/twoFactor.controller.ts
- project/src/web/app/src/components/ui/banner/AlertBanner.vue
- project/src/web/app/src/stores/alert.ts
- project/src/web/app/src/views/2fa/TwoFactorLoginView.vue
- project/src/web/app/src/views/2fa/TwoFactorView.vue
Fixed redirect to login page and now using banners when code is invalid
> 2fa improvements

- project/src/backend/app/src/channels/channels.controller.ts
- project/src/backend/app/src/channels/channels.service.ts
- project/src/backend/app/src/channels/dto/channels.dto.ts
- project/src/web/app/src/components/channels/ChannelLobby.vue
- project/src/web/app/src/components/channels/ChannelSettingsModal.vue
- project/src/web/app/src/components/ui/form/Modal.vue
- project/src/web/app/src/interfaces/chat.interface.ts
add a settings form on channel creation
> feat(channel): add properties on channel creation

- project/src/backend/app/package.json
- project/src/backend/app/src/2fa/twoFactor.controller.ts
- project/src/backend/app/src/2fa/twoFactor.service.ts
- project/src/backend/app/src/auth/auth.service.ts
- project/src/backend/app/yarn.lock
- project/src/web/app/src/components/ui/form/LoginForm.vue
Password is now hashed and 2fa secret should be more secured !
> Hash passwords

- project/src/backend/app/src/channels/channels.controller.ts
- project/src/backend/app/src/channels/channels.service.ts
- project/src/web/app/src/assets/stylesheets/partials/ui/_buttons.scss
- project/src/web/app/src/components/channels/ChannelCard.vue
- project/src/web/app/src/components/channels/ChannelLobby.vue
- project/src/web/app/src/components/icons/index.ts
- project/src/web/app/src/components/icons/svg/XIcon.vue
add leaving channel button which give the owner to another and delete the channel if there is no more member
fix #55
> Leave channel

- project/src/web/app/src/assets/stylesheets/partials/layout/_containers.scss
- project/src/web/app/src/components/user/UsersFilters.vue
- project/src/web/app/src/views/friends/FriendsRequestsSentView.vue
- project/src/web/app/src/views/friends/FriendsRequestsView.vue
- project/src/web/app/src/views/friends/FriendsView.vue
- project/src/web/app/src/views/users/UsersView.vue
> feat(friends): Add the friends interface

- project/src/web/app/src/assets/stylesheets/partials/layout/_containers.scss
- project/src/web/app/src/assets/stylesheets/partials/ui/_buttons.scss
- project/src/web/app/src/components/games/GamesLobby.vue
- project/src/web/app/src/components/layout/header/Header.vue
- project/src/web/app/src/components/layout/header/Nav.vue
- project/src/web/app/src/components/layout/layout/GameLayout.vue
- project/src/web/app/src/components/pong/FieldView.vue
- project/src/web/app/src/components/ui/chart/BarChartCard.vue
- project/src/web/app/src/components/ui/chart/DoughutChartCard.vue
- project/src/web/app/src/components/ui/chart/LineChartCard.vue
- project/src/web/app/src/views/games/GamesView.vue
- project/src/web/app/src/views/users/ProfileView.vue
- project/src/web/app/src/views/users/UsersView.vue
Check responsive on most pages
- Game is now responsive and stylised
- Mobile menu added
TODO:
- need to check for channels/chat when @Tywael will push all the missing features
> 66 featdesign responsive style

- project/src/backend/app/src/games/dto/game.dto.ts
- project/src/backend/app/src/games/games.controller.ts
- project/src/backend/app/src/games/games.service.ts
- project/src/web/app/src/components/games/GamesLobby.vue
- project/src/web/app/src/components/games/GamesSettingsModal.vue
- project/src/web/app/src/components/ui/button/GameProposalButton.vue
- project/src/web/app/src/services/gameServices.ts
- project/src/web/app/src/views/users/ProfileView.vue
- Elo implemented
- Game settings set at the game creation
- Joining game button added
> Feat(game) add game settings on create game and implement elo

- project/src/backend/app/src/socket/socket.gateway.ts
- project/src/web/app/src/assets/stylesheets/partials/ui/_buttons.scss
- project/src/web/app/src/components/games/GamesLobby.vue
- project/src/web/app/src/components/layout/header/Nav.vue
- project/src/web/app/src/components/pong/FieldView.vue
- project/src/web/app/src/services/gameServices.ts
- project/src/web/app/src/views/games/GamesView.vue
- Redirect if game doesnt exist
- Redirect if game finished
- Set alert
- Check if user player has join the game to display btn
- Auto assign player paddle
> 72 feat games settings

- project/src/web/app/src/assets/stylesheets/partials/layout/_containers.scss
- project/src/web/app/src/assets/stylesheets/partials/ui/_buttons.scss
- project/src/web/app/src/components/channels/ChannelList.vue
- project/src/web/app/src/components/channels/ChannelLobby.vue
- project/src/web/app/src/components/channels/ChannelPasswdModal.vue
- project/src/web/app/src/components/channels/ChannelSettingsModal.vue
- project/src/web/app/src/components/chats/ChatConversation.vue
- project/src/web/app/src/components/chats/ChatLobby.vue
- project/src/web/app/src/components/chats/ChatsList.vue
- project/src/web/app/src/components/games/GamesLobby.vue
- project/src/web/app/src/components/ui/banner/AlertBanner.vue
- project/src/web/app/src/components/ui/form/Modal.vue
- project/src/web/app/src/views/HomeView.vue
- project/src/web/app/src/views/users/ProfileView.vue
> 86 fix global style

- project/src/backend/app/src/2fa/twoFactor.controller.ts
- project/src/backend/app/src/auth/auth.controller.ts
- project/src/backend/app/src/auth/auth.service.ts
- project/src/backend/app/src/channels/channels.service.ts
- project/src/backend/app/src/games/games.service.ts
- project/src/backend/app/src/socket/socket.gateway.ts
- project/src/backend/app/src/users/users.service.ts
- project/src/web/app/src/assets/stylesheets/partials/layout/_containers.scss
- project/src/web/app/src/assets/stylesheets/partials/layout/_head.scss
- project/src/web/app/src/components/channels/ChannelList.vue
- project/src/web/app/src/components/channels/ChannelLobby.vue
- project/src/web/app/src/components/chats/ChatConversation.vue
- project/src/web/app/src/components/games/GamesLobby.vue
- project/src/web/app/src/components/pong/FieldView.vue
- project/src/web/app/src/components/ui/button/LoginButton.vue
- project/src/web/app/src/components/ui/button/LogoutButton.vue
- project/src/web/app/src/components/ui/form/LoginForm.vue
- project/src/web/app/src/components/user/MembersList.vue
- project/src/web/app/src/components/user/UserCard.vue
- project/src/web/app/src/components/user/UsersFilters.vue
- project/src/web/app/src/interfaces/game.interface.ts
- project/src/web/app/src/stores/user.ts
- project/src/web/app/src/views/channels/ChannelsLayout.vue
- project/src/web/app/src/views/games/GamesView.vue
- project/src/web/app/src/views/users/ProfileView.vue
- project/src/web/app/src/views/users/UsersView.vue
> 92 live update with socket

- project/src/backend/app/src/auth/auth.controller.ts
- project/src/backend/app/src/socket/socket.gateway.ts
- project/src/web/app/src/App.vue
- project/src/web/app/src/components/chats/ChatConversation.vue
- project/src/web/app/src/components/ui/banner/AlertBanner.vue
- project/src/web/app/src/components/ui/button/GameProposalButton.vue
- project/src/web/app/src/components/ui/button/LoginButton.vue
- project/src/web/app/src/components/ui/button/LogoutButton.vue
- project/src/web/app/src/components/ui/button/RunConversationButton.vue
- project/src/web/app/src/components/ui/form/LoginForm.vue
- project/src/web/app/src/components/user/UsersList.vue
- project/src/web/app/src/interfaces/alert.interface.ts
- project/src/web/app/src/stores/user.ts
- project/src/web/app/src/views/HomeView.vue
- project/src/web/app/src/views/channels/ChannelsLayout.vue
- project/src/web/app/src/views/chats/ChatsLayout.vue
- project/src/web/app/src/views/friends/FriendsRequestsSentView.vue
- project/src/web/app/src/views/friends/FriendsRequestsView.vue
- project/src/web/app/src/views/friends/FriendsView.vue
- project/src/web/app/src/views/games/GamesLayout.vue
- project/src/web/app/src/views/games/GamesView.vue
- project/src/web/app/src/views/users/ProfileView.vue
- project/src/web/app/src/views/users/UsersLayout.vue
- Add live notif
- Update user list when login
> feat(socket): update live event & notif

- project/src/backend/app/src/socket/socket.gateway.ts
- project/src/backend/app/src/socket/socket.module.ts
- project/src/web/app/src/main.ts
- project/src/web/nginx/conf.d/prod.conf
The client is disconnected from websocket if no valide JWT token
> feat(socket): only allow authentified users

- .gitignore
- project/src/backend/app/src/auth/auth.controller.ts
- project/src/backend/app/src/auth/auth.service.ts
- project/src/backend/app/src/main.ts
- project/src/web/app/src/components/games/GamesLobby.vue
- project/src/web/app/src/components/ui/button/LoginButton.vue
- project/src/web/app/src/router/index.ts
- project/src/web/app/src/views/auth/LoginCallbackView.vue
- project/src/web/app/src/views/auth/LoginView.vue
- project/src/web/app/src/views/games/GamesView.vue
- project/src/web/nginx/conf.d/prod.conf
- New way to get tocken from client
> Fix login oauth

- project/src/backend/app/src/socket/socket.gateway.ts
- project/src/web/app/src/views/auth/LoginCallbackView.vue
- project/src/web/app/src/views/chats/ChatsView.vue
> Trigger socket connection
